import { Category } from "visual/config/icons/Categories";

// If you want to update Font Awesome could you can consult a small doc here:  docs/fontAwesome.md
export const categories: Category[] = [
  { title: "Accessibility", id: 1 },
  { title: "Alert", id: 2 },
  { title: "Alphabet", id: 3 },
  { title: "Animals", id: 4 },
  { title: "Arrows", id: 5 },
  { title: "Astronomy", id: 6 },
  { title: "Automotive", id: 7 },
  { title: "Buildings", id: 8 },
  { title: "Business", id: 9 },
  { title: "Camping", id: 10 },
  { title: "Charity", id: 11 },
  { title: "Charts & Diagrams", id: 12 },
  { title: "Childhood", id: 13 },
  { title: "Clothing & Fashion", id: 14 },
  { title: "Coding", id: 15 },
  { title: "Communication", id: 16 },
  { title: "Connectivity", id: 17 },
  { title: "Construction", id: 18 },
  { title: "Design", id: 19 },
  { title: "Devices & Hardware", id: 20 },
  { title: "Disaster", id: 21 },
  { title: "Editing", id: 22 },
  { title: "Education", id: 23 },
  { title: "Emoji", id: 24 },
  { title: "Energy", id: 25 },
  { title: "Files", id: 26 },
  { title: "Film & Video", id: 27 },
  { title: "Food & Beverage", id: 28 },
  { title: "Fruits & Vegetables", id: 29 },
  { title: "Gaming", id: 30 },
  { title: "Gender", id: 31 },
  { title: "Halloween", id: 32 },
  { title: "Hands", id: 33 },
  { title: "Holidays", id: 34 },
  { title: "Household", id: 35 },
  { title: "Humanitarian", id: 36 },
  { title: "Logistics", id: 37 },
  { title: "Maps", id: 38 },
  { title: "Maritime", id: 39 },
  { title: "Marketing", id: 40 },
  { title: "Mathematics", id: 41 },
  { title: "Media & Playback", id: 42 },
  { title: "Medical & Health", id: 43 },
  { title: "Money", id: 44 },
  { title: "Moving", id: 45 },
  { title: "Music & Audio", id: 46 },
  { title: "Nature", id: 47 },
  { title: "Numbers", id: 48 },
  { title: "Photos & Images", id: 49 },
  { title: "Political", id: 50 },
  { title: "Punctuation & Symbols", id: 51 },
  { title: "Religion", id: 52 },
  { title: "Science", id: 53 },
  { title: "Science Fiction", id: 54 },
  { title: "Security", id: 55 },
  { title: "Shapes", id: 56 },
  { title: "Shopping", id: 57 },
  { title: "Social", id: 58 },
  { title: "Spinners", id: 59 },
  { title: "Sports & Fitness", id: 60 },
  { title: "Text & Formatting", id: 61 },
  { title: "Time", id: 62 },
  { title: "Toggle", id: 63 },
  { title: "Transportation", id: 64 },
  { title: "Travel & Hotel", id: 65 },
  { title: "Users & People", id: 66 },
  { title: "Weather", id: 67 },
  { title: "Writing", id: 68 }
];
