import { Category } from "visual/config/icons/Categories";
import { t } from "visual/utils/i18n";

// If you want to update Font Awesome could you can consult a small doc here:  docs/fontAwesome.md
export const getCategories = (): Category[] => [
  { title: t("Accessibility"), id: 1 },
  { title: t("Alert"), id: 2 },
  { title: t("Alphabet"), id: 3 },
  { title: t("Animals"), id: 4 },
  { title: t("Arrows"), id: 5 },
  { title: t("Astronomy"), id: 6 },
  { title: t("Automotive"), id: 7 },
  { title: t("Buildings"), id: 8 },
  { title: t("Business"), id: 9 },
  { title: t("Camping"), id: 10 },
  { title: t("Charity"), id: 11 },
  { title: t("Charts & Diagrams"), id: 12 },
  { title: t("Childhood"), id: 13 },
  { title: t("Clothing & Fashion"), id: 14 },
  { title: t("Coding"), id: 15 },
  { title: t("Communication"), id: 16 },
  { title: t("Connectivity"), id: 17 },
  { title: t("Construction"), id: 18 },
  { title: t("Design"), id: 19 },
  { title: t("Devices & Hardware"), id: 20 },
  { title: t("Disaster"), id: 21 },
  { title: t("Editing"), id: 22 },
  { title: t("Education"), id: 23 },
  { title: t("Emoji"), id: 24 },
  { title: t("Energy"), id: 25 },
  { title: t("Files"), id: 26 },
  { title: t("Film & Video"), id: 27 },
  { title: t("Food & Beverage"), id: 28 },
  { title: t("Fruits & Vegetables"), id: 29 },
  { title: t("Gaming"), id: 30 },
  { title: t("Gender"), id: 31 },
  { title: t("Halloween"), id: 32 },
  { title: t("Hands"), id: 33 },
  { title: t("Holidays"), id: 34 },
  { title: t("Household"), id: 35 },
  { title: t("Humanitarian"), id: 36 },
  { title: t("Logistics"), id: 37 },
  { title: t("Maps"), id: 38 },
  { title: t("Maritime"), id: 39 },
  { title: t("Marketing"), id: 40 },
  { title: t("Mathematics"), id: 41 },
  { title: t("Media & Playback"), id: 42 },
  { title: t("Medical & Health"), id: 43 },
  { title: t("Money"), id: 44 },
  { title: t("Moving"), id: 45 },
  { title: t("Music & Audio"), id: 46 },
  { title: t("Nature"), id: 47 },
  { title: t("Numbers"), id: 48 },
  { title: t("Photos & Images"), id: 49 },
  { title: t("Political"), id: 50 },
  { title: t("Punctuation & Symbols"), id: 51 },
  { title: t("Religion"), id: 52 },
  { title: t("Science"), id: 53 },
  { title: t("Science Fiction"), id: 54 },
  { title: t("Security"), id: 55 },
  { title: t("Shapes"), id: 56 },
  { title: t("Shopping"), id: 57 },
  { title: t("Social"), id: 58 },
  { title: t("Spinners"), id: 59 },
  { title: t("Sports & Fitness"), id: 60 },
  { title: t("Text & Formatting"), id: 61 },
  { title: t("Time"), id: 62 },
  { title: t("Toggle"), id: 63 },
  { title: t("Transportation"), id: 64 },
  { title: t("Travel & Hotel"), id: 65 },
  { title: t("Users & People"), id: 66 },
  { title: t("Weather"), id: 67 },
  { title: t("Writing"), id: 68 }
];
