import { Category } from "visual/config/icons/Categories";

export const categories: Category[] = [
  { title: "Accessibility", id: 1 },
  { title: "Alert", id: 2 },
  { title: "Animals", id: 3 },
  { title: "Arrows", id: 4 },
  { title: "Audio & Video", id: 5 },
  { title: "Automotive", id: 6 },
  { title: "Autumn", id: 7 },
  { title: "Beverage", id: 8 },
  { title: "Buildings", id: 9 },
  { title: "Business", id: 10 },
  { title: "Camping", id: 11 },
  { title: "Charity", id: 12 },
  { title: "Chat", id: 13 },
  { title: "Chess", id: 14 },
  { title: "Childhood", id: 15 },
  { title: "Clothing", id: 16 },
  { title: "Code", id: 17 },
  { title: "Communication", id: 18 },
  { title: "Computers", id: 19 },
  { title: "Construction", id: 20 },
  { title: "Currency", id: 21 },
  { title: "Date & Time", id: 22 },
  { title: "Design", id: 23 },
  { title: "Editors", id: 24 },
  { title: "Education", id: 25 },
  { title: "Emoji", id: 26 },
  { title: "Energy", id: 27 },
  { title: "Files", id: 28 },
  { title: "Finance", id: 29 },
  { title: "Fitness", id: 30 },
  { title: "Food", id: 31 },
  { title: "Fruits & Vegetables", id: 32 },
  { title: "Games", id: 33 },
  { title: "Tabletop Gaming", id: 34 },
  { title: "Genders", id: 35 },
  { title: "Halloween", id: 36 },
  { title: "Hands", id: 37 },
  { title: "Health", id: 38 },
  { title: "Holiday", id: 39 },
  { title: "Hotel", id: 40 },
  { title: "Household", id: 41 },
  { title: "Images", id: 42 },
  { title: "Interfaces", id: 43 },
  { title: "Logistics", id: 44 },
  { title: "Maps", id: 45 },
  { title: "Maritime", id: 46 },
  { title: "Marketing", id: 47 },
  { title: "Mathematics", id: 48 },
  { title: "Medical", id: 49 },
  { title: "Moving", id: 50 },
  { title: "Music", id: 51 },
  { title: "Objects", id: 52 },
  { title: "Payments & Shopping", id: 53 },
  { title: "Pharmacy", id: 54 },
  { title: "Political", id: 55 },
  { title: "Religion", id: 56 },
  { title: "Science", id: 57 },
  { title: "Science Fiction", id: 58 },
  { title: "Security", id: 59 },
  { title: "Shapes", id: 60 },
  { title: "Shopping", id: 61 },
  { title: "Social", id: 62 },
  { title: "Spinners", id: 63 },
  { title: "Sports", id: 64 },
  { title: "Spring", id: 65 },
  { title: "Status", id: 66 },
  { title: "Summer", id: 67 },
  { title: "Toggle", id: 68 },
  { title: "Travel", id: 69 },
  { title: "Users & People", id: 70 },
  { title: "Vehicles", id: 71 },
  { title: "Weather", id: 72 },
  { title: "Winter", id: 73 },
  { title: "Writing", id: 74 }
];
