import { checkValue2 } from "visual/utils/checkValue";

export enum ElementTypes {
  Text = "Text",
  Image = "Image",
  Button = "Button",
  Icon = "Icon",
  Spacer = "Spacer",
  Map = "Map",
  AnimatedHeadline = "AnimatedHeadline",
  FormField = "FormField",
  FormFields = "FormFields",
  Form2 = "Form2",
  Line = "Line",
  Menu = "Menu",
  MenuSimple = "MenuSimple",
  Login = "Login",
  Translation = "Translation",
  Posts = "Posts",
  Search = "Search",
  ImageGallery = "ImageGallery",
  Video = "Video",
  Audio = "Audio",
  VideoPlaylist = "VideoPlaylist",
  IconText = "IconText",
  Lottie = "Lottie",
  Embed = "Embed",
  StarRating = "StarRating",
  Alert = "Alert",
  Counter = "Counter",
  Countdown2 = "Countdown2",
  ProgressBar = "ProgressBar",
  Calendly = "Calendly",
  Carousel = "Carousel",
  CarouselItems = "Carousel.Items",
  Tabs = "Tabs",
  Tab = "Tab",
  Accordion = "Accordion",
  AccordionItem = "AccordionItem",
  Switcher = "Switcher",
  SwitcherTab = "SwitcherTab",
  Table = "Table",
  Timeline = "Timeline",
  Facebook = "Facebook",
  Twitter = "Twitter",
  FacebookComments = "FacebookComments",
  Columns = "Columns",
  Row = "Row",
  AssetsPosts = "AssetsPosts",
  ProtectedPage = "ProtectedPage",
  ResetPassword = "ResetPassword",
  PostTitle = "WPPostsTitle",
  Cart = "Cart",
  MyAccount = "MyAccount",
  RichText = "RichText",
  Column = "Column",
  Leadific = "Leadific",
  StoryItem = "StoryItem",
  StoryButton = "StoryButton",
  StoryIcon = "StoryIcon",
  StoryEmbed = "StoryEmbed",
  StoryText = "StoryText",
  StoryMap = "StoryMap",
  StoryProgressBar = "StoryProgressBar",
  StoryLine = "StoryLine",
  StoryCountdown2 = "StoryCountdown2",
  StoryCounter = "StoryCounter",
  StoryShape = "StoryShape",
  StoryForm2 = "StoryForm2",
  StoryStarRating = "StoryStarRating",
  StoryLottie = "StoryLottie",
  StoryImage = "StoryImage",
  StoryVideo = "StoryVideo",
  StoryLeadific = "StoryLeadific",
  WOOProductTitle = "WOOProductTitle",
  WOOExcerpt = "WOOExcerpt",
  WOOProductContent = "WOOProductContent",
  WOOPrice = "WOOPrice",
  WOOGallery = "WOOGallery",
  WOOAddToCart = "WOOAddToCart",
  WOOStock = "WOOStock",
  WOOSku = "WOOSku",
  WOOProductMeta = "WOOProductMeta",
  WOORating = "WOORating",
  WOOAttributes = "WOOAttributes",
  WOOUpsell = "WOOUpsell",
  WOOBreadcrumbs = "WOOBreadcrumbs",
  WOOCategories = "WOOCategories",
  WOOPages = "WOOPages",
  WOOCart = "WOOCart",
  WPPostContent = "WPPostContent",
  WPPostInfo = "WPPostInfo",
  WPBreadcrumbs = "WPBreadcrumbs",
  WPPostNavigation = "WPPostNavigation",
  WPFeaturedImage = "WPFeaturedImage",
  WPSidebar = "WPSidebar",
  WPCustomShortcode = "WPCustomShortcode",
  UserFirstName = "UserFirstName",
  UserLastName = "UserLastName",
  UserEmail = "UserEmail",
  UserPhoneNumber = "UserPhoneNumber",
  UserRoles = "UserRoles",
  UserUsername = "UserUsername",
  Products = "Products",
  Review = "Review",
  Archive = "Archive",
  AddToCart = "AddToCart",
  PostExcerpt = "WPPostExcerpt",
  ShopifyDescription = "ShopifyDescription",
  ShopifyImage = "ShopifyImage",
  BlogPostExcerpt = "BlogPostExcerpt",
  Variant = "Variant",
  PostInfo = "PostInfo",
  PostNavigation = "PostNavigation",
  Breadcrumbs = "Breadcrumbs",
  Radio = "Radio",
  Section = "Section",
  SectionItem = "SectionItem",
  SectionMegaMenu = "SectionMegaMenu",
  SectionPopup2 = "SectionPopup2",
  SectionPopup = "SectionPopup",
  SectionHeader = "SectionHeader",
  SectionHeaderItem = "SectionHeaderItem",
  SectionHeaderStickyItem = "SectionHeaderStickyItem",
  SectionFooter = "SectionFooter",
  Story = "Story",
  Checkbox = "Checkbox",
  Calculated = "Calculated",
  TableOfContents = "TableOfContents",
  Flipbox = "Flipbox",
  FlipboxItems = "Flipbox.Items",
  FlipboxItem = "FlipboxItem",
  FlipboxItemItems = "FlipboxItem.Items",
  ShareButton = "ShareButton",
  ShareButtonItem = "ShareButtonItem",
  ShareButtonItemItems = "ShareButton.Items",
  Paypal = "Paypal",
  Form2Steps = "Form2Steps",
  Form2StepsItems = "Form2Steps.Items",
  Form2Step = "Form2Step",
  VideoPlaylistItem = "VideoPlaylistItem",
  Form2FieldOption = "Form2FieldOption",
  Form2Field = "Form2Field",
  Form2Fields = "Form2Fields",
  Select = "Select",
  Hidden = "Hidden",
  Form2FieldItems = "Form2FieldItems",
  InstagramFeed = "InstagramFeed",
  GlobalBlock = "GlobalBlock",
  LinkedinFeed = "LinkedinFeed",
  Chart = "Chart",
  EmbedCode = "EmbedCode",
  ThirdParty = "ThirdParty",
  ThirdPartyItems = "ThirdParty.Items",
  Cloneable = "Cloneable",
  Wrapper = "Wrapper",
  StoryWrapper = "StoryWrapper",
  Page = "Page",
  PagePopup = "PagePopup",
  PageStory = "PageStory",
  TimelineTab = "TimelineTab",
  Shape = "Shape",
  SoundCloud = "SoundCloud",
  Countdown = "Countdown",
  MenuItem = "MenuItem",
  LoginField = "LoginField",
  RegisterField = "RegisterField",
  ForgotPasswordField = "ForgotPasswordField",
  ResetPasswordField = "ResetPasswordField",
  Form = "Form",
  FacebookButton = "FacebookButton",
  FacebookEmbed = "FacebookEmbed",
  FacebookPage = "FacebookPage",
  FacebookGroup = "FacebookGroup",
  TableBody = "TableBody",
  TableHead = "TableHead",
  TableAside = "TableAside",
  TableRow = "TableRow",
  TableCol = "TableCol",
  NotFound = "NotFound",
  WPNavigation = "WPNavigation",
  WOOProductPage = "WOOProductPage",
  WOOProducts = "WOOProducts",
  WPPosts = "WPPosts",
  Wrapper2 = "Wrapper2",

  // Shopify
  ShoppingBag = "ShoppingBag",
  ShopPosts = "ShopPosts",
  ShopCategories = "ShopCategories",
  ShopifyTitle = "ShopifyTitle",
  Product = "Product",
  Quantity = "Quantity",
  ProductMetafield = "ProductMetafield",
  Vendor = "Vendor",
  BlogPostMeta = "BlogPostMeta",
  Price = "Price",
  ProductList = "ProductList",
  CollectionList = "CollectionList",
  BlogPostList = "BlogPostList",

  // MinistryBrands
  MinistryBrandsGroupLayout = "MinistryBrandsGroupLayout",
  MinistryBrandsGroupSlider = "MinistryBrandsGroupSlider",
  MinistryBrandsEventLayout = "MinistryBrandsEventLayout",
  MinistryBrandsEventCalendar = "MinistryBrandsEventCalendar",
  MinistryBrandsSermonLayout = "MinistryBrandsSermonLayout",
  MinistryBrandsSermonList = "MinistryBrandsSermonList",
  MinistryBrandsStaffList = "MinistryBrandsStaffList",
  MinistryBrandsSermonFeatured = "MinistryBrandsSermonFeatured",
  MinistryBrandsSermonDetail = "MinistryBrandsSermonDetail",
  MinistryBrandsGroupList = "MinistryBrandsGroupList",
  MinistryBrandsGroupDetail = "MinistryBrandsGroupDetail",
  MinistryBrandsEventFeatured = "MinistryBrandsEventFeatured",
  MinistryBrandsGroupFeatured = "MinistryBrandsGroupFeatured",
  MinistryBrandsEventList = "MinistryBrandsEventList",
  MinistryBrandsEventDetail = "MinistryBrandsEventDetail",
  MinistryBrandsFormWidget = "MinistryBrandsFormWidget",
  MinistryBrandsPrayerWidget = "MinistryBrandsPrayerWidget",
  MinistryBrandsStaffFeatured = "MinistryBrandsStaffFeatured",
  MinistryBrandsArticleLayout = "MinistryBrandsArticleLayout",
  MinistryBrandsStaffLayout = "MinistryBrandsStaffLayout",
  MinistryBrandsStaffDetail = "MinistryBrandsStaffDetail",
  MinistryBrandsArticleList = "MinistryBrandsArticleList",
  MinistryBrandsArticleDetail = "MinistryBrandsArticleDetail",
  MinistryBrandsArticleFeatured = "MinistryBrandsArticleFeatured",

  // Ecwid
  EcwidProducts = "EcwidProducts",
  EcwidShoppingBag = "EcwidShoppingBag",
  EcwidSearch = "EcwidSearch",
  EcwidPrice = "EcwidPrice",
  EcwidAddToCart = "EcwidAddToCart",
  EcwidProduct = "EcwidProduct",
  EcwidCart = "EcwidCart",
  EcwidMyAccount = "EcwidMyAccount",
  EcwidFavorites = "EcwidFavorites",

  ImageComparison = "ImageComparison",
}

export const MinistryBrandsGroups = [
  ElementTypes.MinistryBrandsGroupLayout,
  ElementTypes.MinistryBrandsGroupSlider,
  ElementTypes.MinistryBrandsEventLayout,
  ElementTypes.MinistryBrandsEventCalendar,
  ElementTypes.MinistryBrandsSermonLayout,
  ElementTypes.MinistryBrandsSermonList,
  ElementTypes.MinistryBrandsStaffList,
  ElementTypes.MinistryBrandsSermonFeatured,
  ElementTypes.MinistryBrandsSermonDetail,
  ElementTypes.MinistryBrandsGroupList,
  ElementTypes.MinistryBrandsGroupDetail,
  ElementTypes.MinistryBrandsEventFeatured,
  ElementTypes.MinistryBrandsGroupFeatured,
  ElementTypes.MinistryBrandsEventList,
  ElementTypes.MinistryBrandsEventDetail,
  ElementTypes.MinistryBrandsFormWidget,
  ElementTypes.MinistryBrandsPrayerWidget,
  ElementTypes.MinistryBrandsStaffFeatured,
  ElementTypes.MinistryBrandsArticleLayout,
  ElementTypes.MinistryBrandsStaffLayout,
  ElementTypes.MinistryBrandsStaffDetail,
  ElementTypes.MinistryBrandsArticleList,
  ElementTypes.MinistryBrandsArticleDetail,
  ElementTypes.MinistryBrandsArticleFeatured
];

export const EcwidGroups = [
  ElementTypes.EcwidProducts,
  ElementTypes.EcwidShoppingBag,
  ElementTypes.EcwidSearch,
  ElementTypes.EcwidPrice,
  ElementTypes.EcwidAddToCart,
  ElementTypes.EcwidProduct,
  ElementTypes.EcwidCart,
  ElementTypes.EcwidMyAccount,
  ElementTypes.EcwidFavorites
];

export const ShopifyGroups = [
  ElementTypes.AddToCart,
  ElementTypes.Price,
  ElementTypes.Vendor,
  ElementTypes.Quantity,
  ElementTypes.ProductMetafield,
  ElementTypes.BlogPostMeta,
  ElementTypes.Variant,
  ElementTypes.ShoppingBag,
  ElementTypes.ShopPosts,
  ElementTypes.ShopCategories,
  ElementTypes.ShopifyTitle,
  ElementTypes.Product,
  ElementTypes.Quantity,
  ElementTypes.ProductMetafield,
  ElementTypes.Vendor
];

export const readElementType = checkValue2(ElementTypes);
